version: "3.8"
services:
    selenium:
        image: selenium/standalone-firefox
        container_name: firefox
        ports:
            - "4444:4444"
        networks:
            - grid

    botapp:
        image: botapp
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - selenium
        networks:
            - grid
        volumes:
            - "./main.py:/main.py"
            - "/tmp:/tmp"
        command: ["python3", "/main.py"]

networks:
    grid:
