version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:3.6-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - grid

    mongodb:
        image: mongo:3.6.23
        container_name: mongodb
        hostname: mongodb
        ports:
            - "27017:27017"
        networks:
            - grid
        env_file:
            - mongodb.env

    selenium:
        image: selenium/standalone-firefox
        container_name: firefox
        ports:
            - "4444:4444"
        networks:
            - grid

    publisherapp:
        image: publisherapp
        build:
            context: ./publisherapp
            dockerfile: Dockerfile
        depends_on:
            - mongodb
            - rabbitmq
        networks:
            - grid
        env_file:
            - mongodb.env
        command: ["python3", "-B", "main.py"]
        volumes:
            - "./publisherapp/main.py:/main.py"

    botapp:
        image: botapp
        build:
            context: ./botapp
            dockerfile: Dockerfile
        depends_on:
            - selenium
            - mongodb
            - publisherapp
        networks:
            - grid
        env_file:
            - mongodb.env
        volumes:
            - "./botapp:/app"
        working_dir: /app
        command: ["python3", "-B", "main.py"]

networks:
    grid:
        driver: bridge
