version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:3.6-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - grid

    mongodb:
        image: mongo:3.6.23
        container_name: mongodb
        hostname: mongodb
        ports:
            - "27017:27017"
        networks:
            - grid
        env_file:
            - mongodb.env

    selenium:
        image: selenium/standalone-firefox
        container_name: firefox
        ports:
            - "4444:4444"
        networks:
            - grid

    botapp:
        image: botapp
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - selenium
            - mongodb
        networks:
            - grid
        env_file:
            - mongodb.env
        volumes:
            - "./main.py:/main.py"
            - "/tmp:/tmp"
        command: ["python3", "/main.py"]

networks:
    grid:
        driver: bridge
